# @package _global_

logging:
  level: DEBUG
  log_dir: ${log_dir}
  rotation: ${log_rotation}
  retention: ${log_retention}

wandb_config:
  _target_: gigaevo.utils.trackers.configs.WBConfig
  project: evo
  name: ${tag}

redis_metrics_config:
  _target_: gigaevo.utils.trackers.configs.RedisMetricsConfig
  redis_url: redis://${redis.host}:${redis.port}/${redis.db}
  key_prefix: ${problem.name}:metrics

writer:
  _target_: gigaevo.utils.trackers.init_wandb_redis
  wandb_cfg: ${wandb_config}
  redis_cfg: ${redis_metrics_config}
