# @package _global_

# Redis connection parameters
redis:
  host: localhost
  port: 6379
  db: 0
  resume: false
# Redis storage configuration
redis_storage:
  _target_: gigaevo.database.redis_program_storage.RedisProgramStorage
  config:
    _target_: gigaevo.database.redis_program_storage.RedisProgramStorageConfig
    redis_url: redis://${redis.host}:${redis.port}/${redis.db}
    key_prefix: ${problem.name}
    max_connections: ${redis_max_connections}
    connection_pool_timeout: ${redis_connection_pool_timeout}
    health_check_interval: ${redis_health_check_interval}
    max_retries: ${redis_max_retries}
    retry_delay: ${redis_retry_delay}
  writer: ${writer}
